esphome:
  project:
    name: tater.respeaker_xvf3800
    version: ${firmware_version}
  min_version: 2026.4.0
  on_boot:
    - priority: 375
      then:
        - sensor.template.publish:
            id: next_timer
            state: -1
        # Run the script to refresh the LED status
        - script.execute: control_leds
        # If after 10 minutes, the device is still initializing (It did not yet connect to Home Assistant), turn off the init_in_progress variable and run the script to refresh the LED status
        - delay: 10min
        - if:
            condition:
              lambda: return id(init_in_progress);
            then:
              - lambda: id(init_in_progress) = false;
              - script.execute: control_leds
    - priority: -100
      then:
        - lambda: |-
            auto call = id(alarm_action).make_call();
            call.set_option(id(saved_alarm_action));
            call.perform();
        - lambda: |-
            setenv("TZ", id(saved_time_zone).c_str(), 1);
            tzset();

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  variant: esp32s3
  flash_size: 8MB
  partitions:
    - name: mww_model_a
      type: data
      subtype: 0x40
      size: 0x80000
    - name: mww_model_b
      type: data
      subtype: 0x41
      size: 0x80000
  framework:
    type: esp-idf
    version: recommended
    components:
      - espressif/esp-nn==1.1.2
    sdkconfig_options:
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"

      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      # Considerably speeds up mWW at the cost of using more PSRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"

      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"  # TLS1.3 support isn't enabled by default in IDF 5.1.5

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  use_address: ${ha_voice_ip}
  id: wifi_id
  fast_connect: ${hidden_ssid}
  power_save_mode: none
  reboot_timeout: 10min
  on_connect:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_disconnect:
    - script.execute: control_leds
network:
  enable_ipv6: true

logger:
  level: debug
  initial_level: debug
  logs:
    sensor: WARN
    voice_assistant: INFO
    micro_wake_word: INFO
    i2s_audio: WARN
    respeaker_xvf3800: INFO

api:
  id: api_id
  actions:
    - action: set_led_color
      variables:
        red: float
        green: float
        blue: float
      then:
        - lambda: |-
            id(user_led_ring_color_r) = std::min(255.0f, std::max(0.0f, red));
            id(user_led_ring_color_g) = std::min(255.0f, std::max(0.0f, green));
            id(user_led_ring_color_b) = std::min(255.0f, std::max(0.0f, blue));
        - select.set:
            id: user_led_color_preset
            option: "Custom"
    - action: start_va
      then:
        - voice_assistant.start
    - action: stop_va
      then:
        - voice_assistant.stop
    - action: start_push_to_intercom
      then:
        - script.execute: start_push_to_intercom
    - action: stop_push_to_intercom
      then:
        - script.execute: stop_push_to_intercom
    - action: set_time_zone
      variables:
        posix_time_zone: string
      then:
        - lambda: |-
            setenv("TZ", posix_time_zone.c_str(), 1);
            tzset();
            id(saved_time_zone) = posix_time_zone;
            id(publish_current_time).execute();
  on_client_connected:
    - script.execute: control_leds
  on_client_disconnected:
    - script.execute: control_leds

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

i2c:
  - id: internal_i2c
    sda: GPIO5
    scl: GPIO6
    scan: true
    frequency: 100kHz

psram:
  mode: octal
  speed: 80MHz
  ignore_not_found: false

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Every 1 minute
      - seconds: 0
        then:
          - script.execute: check_alarm
    on_time_sync:
      - script.execute: publish_current_time

datetime:
  # schedule the alarm time from Home Assistant
  - platform: template
    icon: mdi:bell-ring
    name: "Alarm time"
    id: alarm_time
    type: time
    initial_value: "00:00:00"
    restore_value: true
    optimistic: true
    internal: false
    set_action:
      then:
        - switch.turn_on: alarm_on
