globals:
  - id: remote_timer_total_seconds
    type: int
    restore_value: yes
    initial_value: "0"

  - id: remote_timer_remaining_seconds
    type: int
    restore_value: yes
    initial_value: "0"

  - id: remote_timer_running
    type: bool
    restore_value: yes
    initial_value: "false"

interval:
  - interval: 1s
    then:
      - if:
          condition:
            lambda: return id(remote_timer_running);
          then:
            - lambda: |-
                if (id(remote_timer_remaining_seconds) > 0) {
                  id(remote_timer_remaining_seconds) -= 1;
                }
            - script.execute: control_leds
            - if:
                condition:
                  lambda: return id(remote_timer_running) && (id(remote_timer_remaining_seconds) <= 0);
                then:
                  - lambda: |-
                      id(remote_timer_running) = false;
                  - switch.turn_on: timer_ringing
                  - script.execute: control_leds

number:
  - platform: template
    id: remote_timer_seconds
    name: "Remote Timer Seconds"
    icon: mdi:timer
    min_value: 0
    max_value: 7200
    step: 1
    optimistic: true
    restore_value: true
    set_action:
      - lambda: |-
          int v = (int) x;
          if (v < 0) v = 0;
          id(remote_timer_total_seconds) = v;
          id(remote_timer_remaining_seconds) = v;
          id(control_leds).execute();

binary_sensor:
  - platform: template
    id: remote_timer_running_sensor
    name: "Remote Timer Running"
    device_class: running
    lambda: |-
      return id(remote_timer_running);

sensor:
  - platform: template
    id: remote_timer_remaining_seconds_sensor
    name: "Remote Timer Remaining Seconds"
    icon: mdi:timer-sand
    unit_of_measurement: s
    accuracy_decimals: 0
    update_interval: 1s
    lambda: |-
      return id(remote_timer_remaining_seconds);

button:
  - platform: template
    id: remote_timer_start
    name: "Remote Timer Start"
    icon: mdi:play
    on_press:
      - lambda: |-
          id(remote_timer_remaining_seconds) = id(remote_timer_total_seconds);
          id(remote_timer_running) = (id(remote_timer_remaining_seconds) > 0);
      - switch.turn_off: timer_ringing
      - script.execute: control_leds

  - platform: template
    id: remote_timer_cancel
    name: "Remote Timer Cancel"
    icon: mdi:stop
    on_press:
      - lambda: |-
          id(remote_timer_running) = false;
          id(remote_timer_total_seconds) = 0;
          id(remote_timer_remaining_seconds) = 0;
      - switch.turn_off: timer_ringing
      - script.execute: control_leds
