
include(${CMAKE_CURRENT_LIST_DIR}/dac/dac.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SATELLITE1/SATELLITE1.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SATELLITE1-USB/SATELLITE1-USB.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/XCORE-AI-EXPLORER/XCORE-AI-EXPLORER.cmake)

